apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    basicAuth: false
    isDefault: false
    database: "*"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "8.0.0"
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
    secureJsonData: {}
    version: 1
    editable: true

  - name: elasticsearch-chat
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    basicAuth: false
    isDefault: false
    database: "chat-messages-*"
    jsonData:
      interval: Daily
      timeField: "timestamp"
      esVersion: "8.0.0"
      maxConcurrentShardRequests: 5
      logMessageField: user_message
      logLevelField: level
      includeFrozen: false
    secureJsonData: {}
    version: 2
    uid: elasticsearch-chat
    editable: true